### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by glyg** [centuri-engineering/impomero#1]
- [x] allow for image based annotation
- [x] De-duplicate map annotations
- [x] better (i.e. working) persistence for the import table

**Comment by glyg** [comment]
closed by dddb759d6

- Annotation is now image based
- Map Annotations are now updated not duplicated
- Import information is manage by a sqlite db
